language: python
dist: xenial
cache: pip
python:
  - 3.5
  - 3.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black; fi
  - python setup.py install
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black --check --verbose .; fi
  - python setup.py test
